# Generated by Django 4.1.7 on 2023-05-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Code', models.CharField(max_length=150)),
                ('linenos', models.BooleanField(unique=True)),
                ('Language', models.CharField(max_length=100)),
                ('Style', models.CharField(max_length=50)),
            ],
        ),
    ]
